use_frameworks!

target 'BLAMCurrencyPicker_Example' do
  pod 'BLAMCurrencyPicker', :path => '../'

  target 'BLAMCurrencyPicker_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
